### ISSUE TITLE
Player movement is not smooth

### ISSUE THREAD

**Issue by HikingCarrot7** [CherrySoftMX/Brick-Breaker#3]

**Comment by Shadic78** [comment]
Hi, could you be more specific about this issue?
What's not smooth?, do you think the player horizontal displacement isn't smooth or is it the keyboard/touch input not being smooth?

**Comment by HikingCarrot7** [comment]
When you start moving towards the left and press to move towards the right (without releasing the left button), the movement is as expected and the player moves towards the right. However, upon releasing the left button, the player stops and the right button needs to be **pressed again** to continue the movement. 

I believe this issue severely impacts the gameplay due to the fact that it can be very difficult to reposition the player when a change in direction occurs.

**Comment by Shadic78** [comment]
Hi @HikingCarrot7, I have been working on this issue and I patched it on #9 by adding a custom input manager to add support for multi-key input. Feel free to take a look to close the issue and report any more issues you may find. :thumbsup:
